<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<script src="${staticsUrl}/zz99/scripts/zz99App/ajustes/rup.table.editForm.ajustes.js" type="text/javascript"></script>
<script src="${staticsUrl}/zz99/scripts/zz99App/ajustes/rupTableAdjust.js" type="text/javascript"></script>
<script src="${staticsUrl}/zz99/scripts/zz99App/ajustes/rup.report.ajustes.js" type="text/javascript"></script>

<!-- Cargador del layout para el idioma, menu y migas -->
<script src="${staticsUrl}/zz99/scripts/zz99App/_layoutLoader.js" type="text/javascript"></script>
<script src="${staticsUrl}/zz99/scripts/zz99App/utils/blockScreenLoadUtils.js" type="text/javascript"></script>
<script src="${staticsUrl}/zz99/scripts/zz99App/utils/utils.js" type="text/javascript"></script>
<script src="${staticsUrl}/zz99/scripts/zz99App/utils/rup.validaciones.js" type="text/javascript"></script>
<script src="${staticsUrl}/zz99/scripts/zz99App/utils/fitText.js" type="text/javascript"></script>
